# Site wide configuration

title: Academic Website of Artun Dalyan
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Artun Dalyan
  avatar: bio-photo.jpg
  bio: "My name is Artun Dalyan. I have graduated from UC Berkeley in EECS major. During my childhood, reading about new scientific advancements and new automobiles in magazines was my hobby and that’s why I wanted to be an engineer. I applied to UC Berkeley as an undeclared engineer. By learning more about different majors in my first year, I declared my major as Electrical Engineering and Computer Science. Working with circuits is my passion that’s why I pursue my career in the field of Electrical Engineering. I have done projects on analog and digital circuit designs such as CPU design on a Field Programmable Gate Array and Operational Amplifiers. I am hoping to be a part of Brain Machine Interface research in the future. I think the mystery of our brain has yet to be solved. However, before getting involved with this research, my priority is to gain more experience in analog hardware designs in the industry."
  email: artundalyan21@berkeley.edu
  # Do not include the @ symbol in your Twitter username
  twitter: swimmerART
  linkedin: artundalyan
  github: swimmerART
  orcid: # ID Number (ex. 0000-0000-0000-0000)
  researchgate: #username
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
  facebook: #username
  instagram: #username
  bing-verify:
  stackoverflow: #123456/username from a "https://stackoverflow.com/users/123456/username" link
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#CC0000'
lowlight-color: '#000'

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: #yes
  cc-by-nc: yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
